# Generated by Django 4.0.2 on 2022-02-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
