# Generated by Django 4.0.2 on 2022-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main1', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('p_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=10)),
                ('p_descp', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
